### ISSUE TITLE
gettext.translation

### ISSUE THREAD

**Issue by sandeshputtaraju** [iver56/python-i18n-basics#1]
Trying to translate the text, but I am getting below error:

raise OSError(ENOENT, 'No translation file found for the domain', domain)

FileNotFoundError: [Errno 2] No translation file found for domain: 'helloworld'

**Comment by iver56** [comment]
You have to run `pybabel compile --domain=helloworld --directory=locale --use-fuzzy` before you run `python hello_world.py`. It's in the readme. Please reopen if that did not fix your issue.
